//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetSale
    {
        public int Invoice { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
