//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellDrug
    {
        public int Id { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> DrugId { get; set; }
        public Nullable<int> DrugCount { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
